### ISSUE TITLE
SignalR Negotiate | build compile issue

### ISSUE THREAD

**Issue by robcwaldron** [JamesRandall/FunctionMonkey#114]
When using the command and handlers for SignalR, the build fails to compile. This is on the latest beta build.

.Functions(functions => functions
                    .SignalR(signalR => signalR
                        .Negotiate<SignalRNegotiateCommand>("/negotiate")
                    )

![image](https://user-images.githubusercontent.com/1562797/71775614-3c064100-2fcf-11ea-8207-a9ed19378527.png)

**Comment by mdg215199** [comment]
I think you need to add the extra hub name.
.Negotiate("/negotiate", "hubName")

That way, it seems to work.  On handling the handler itself so you can control the negotiate, this works
.Negotiate<SignalRNegotiateCommand>("/negotiate", AuthorizationTypeEnum.Anonymous, HttpMethod.Post)

**Comment by robcwaldron** [comment]
Thanks, so I tried it that. I still seem to get the same error when using the handler way. Maybe I'm missing something simple?

![image](https://user-images.githubusercontent.com/1562797/71775966-c4d3ab80-2fd4-11ea-81c9-b42f68ea0c80.png)

**Comment by robcwaldron** [comment]
Okay, I've been attempting to debug this. For more clarity, I'm using Authorization too. When I comment out the below, the issue goes away. Still trying to find what the cause is though. I'll report back if I can find it.

 .Authorization(authorization => authorization
                    .AuthorizationDefault(AuthorizationTypeEnum.TokenValidation)
                    .AddOpenIdConnectTokenValidator($"https://{Domain}/oauth2/default/.well-known/oauth-authorization-server", Audience)
                )

**Comment by robcwaldron** [comment]
Okay, I've tracked down the issue to the handlebars template here. Not overly familiar with the behind the scenes of FunctionMonkey yet, but I'll see if I can work out what it's all doing.

![image](https://user-images.githubusercontent.com/1562797/71776271-411cbd80-2fda-11ea-9a96-1a78c459d441.png)

**Comment by mdg215199** [comment]
Is the example you gave earlier, is that what you are using?

.SignalR(signalR => signalR
.Negotiate("/negotiate")

Also, what do you have set up in the csproj?   As i can replicate the issue.  Oh, one other question, do you need to validate your openid bearer?  I tried testing on both scenarios (anonymous with no auth, and also, another with the authorization in place for http w/ anonymous on the signalr).

**Comment by robcwaldron** [comment]
Hey @mdg215199 

Here's the snippet from the FunctionAppConfiguration and the csproj. Yes, ideally openid is used here for validation. 

![image](https://user-images.githubusercontent.com/1562797/71882064-64cd3880-317f-11ea-8b15-7d96a4bf53fd.png)

![image](https://user-images.githubusercontent.com/1562797/71882094-79a9cc00-317f-11ea-9eb7-cdfada079427.png)

A

**Comment by JamesRandall** [comment]
This should be resolved as part of beta 3 - its on NuGet now. Let me know if that helps. I was able to replicate in the acceptance tests and resolve so marking this as closed. Please reopen if you continue to face issues.

There were some breaking changes in the Microsoft.IdentityModel.Tokens package and its dependencies which rather unhelpfully they have not highlighted through semver. I'd updated to 5.6 but in an underlying JWT package (also a minor version bump) they've removed a method that the SignalR binding depends on. Resolution was to downgrade to 5.5.

**Comment by robcwaldron** [comment]
Thanks @JamesRandall . Testing this now

**Comment by robcwaldron** [comment]
@JamesRandall - this issue still exists in beta3. It's still reporting System.Runtime.Extensions Version 4.2.2.0 is not present.

**Comment by robcwaldron** [comment]
@JamesRandall - 5.6 still seems to be referenced?

![image](https://user-images.githubusercontent.com/1562797/72056744-e6a49980-3318-11ea-8bb5-48aee3ec5a7a.png)

**Comment by JamesRandall** [comment]
Aaarrrggh. I’d checked deps too. I’ll take another look. Thanks for letting me know!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JamesRandall** [comment]
That is very very strange. In my csproj 5.5 is definitely referenced:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/236247/72062102-6b6ec380-32d7-11ea-89d0-984b8cd1ecf7.png">

**Comment by JamesRandall** [comment]
I've just tried creating a new project and adding the packages, including the token validator - it all seems to work ok:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/236247/72063391-0072bc00-32da-11ea-9d4e-945ac393b8c0.png">

Also passes in the acceptance tests.

Could you share your csproj file?

**Comment by robcwaldron** [comment]
I've just created a new project with beta4, and i'm still getting IdentityModel.Tokens 5.6.0
![image](https://user-images.githubusercontent.com/1562797/72317011-ad3aa800-36e3-11ea-9c0c-6cb57b336319.png)

csproj here:
![image](https://user-images.githubusercontent.com/1562797/72317038-bd528780-36e3-11ea-96f2-9dfa8cc91b14.png)

**Comment by robcwaldron** [comment]
@JamesRandall - Okay, so I've tried to mock up what you've done in your screenshots. That's working fine. Where I still get this error is if I do this:

![image](https://user-images.githubusercontent.com/1562797/72317886-61d5c900-36e6-11ea-9bba-1cae44679c71.png)

Command:
![image](https://user-images.githubusercontent.com/1562797/72317921-803bc480-36e6-11ea-97f5-81be7a38a6d5.png)

Handler:
![image](https://user-images.githubusercontent.com/1562797/72317899-6dc18b00-36e6-11ea-9cf1-0b98ca2f1e29.png)

**Comment by JamesRandall** [comment]
Thanks - I’m travelling today but I’ll take a look at that ASAP.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
