### ISSUE TITLE
No job functions found.

### ISSUE THREAD

**Issue by themajix** [JamesRandall/FunctionMonkey#16]
Hi James. I've cloned the full FunctionMonkey solution locally and have set GettingStartedSample project as the startup project. I've done no other modifications to the source code and configuration. When running the project I get the following message in the function runtime terminal (version 2.0.12134.0):

"No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.)."

As a result no URL is provided for running the application. Could that be related to the changes in the Functions runtime since the latest version of FunctionMonkey was released?

**Comment by JamesRandall** [comment]
I think you've fallen foul of one of the things on my to do list! The packages they reference were out of date. I've just bumped them to the new versions and committed the changes.

If you do a pull that should fix it for you - if it doesn't give me a shout and I'll reopen this.

Thanks for reporting it.

**Comment by themajix** [comment]
Thank you for your quick response. Have those changes been pushed already? I still see the latest commit as of 29 days ago.

**Comment by JamesRandall** [comment]
Give it a go now... hadn't noticed an error message in my console!

**Comment by themajix** [comment]
It's weird. It still behaves the same way: "No job functions found..." I'm using the latest version of Azure Functions and Web Jobs Core (15.10.2046.0) with Azure Function Core Tools 2.1.748 . I also tried it after I updated all of NuGet packages in the solution to their latest versions, but still the same.
It may also worth it to mention that the very first message I get in the function runtime terminal is this: 

"your worker runtime is not set. As of 2.0.1-beta.26 a worker runtime setting is required.
Please run `func settings add FUNCTIONS_WORKER_RUNTIME <option>` or add FUNCTIONS_WORKER_RUNTIME to your local.settings.json
Available options: dotnet, node, python"

**Comment by themajix** [comment]
All works well now - just as expected! Thank you very much James. BTW this work is very inspiring and I have learned so much by studying it. - Thank you!

**Comment by JamesRandall** [comment]
Thanks - that's much appreciated. As is the time you took to provide feedback and work with me to get this sorted. If anything else comes up you can catch me here or over on twitter (@azuretrenches).
