### ISSUE TITLE
Internal Server Error response

### ISSUE THREAD

**Issue by ixelero** [JamesRandall/FunctionMonkey#63]
Hi, James

When passing string data to route http://localhost:7071/api/v1/vendors/{id} (where {id} is integer) I'll get internal server error.
![image](https://user-images.githubusercontent.com/26705542/57512427-42df9580-7314-11e9-96bd-b78253996897.png)
I hope you could help with this issue. Thanks in advance.

**Comment by mcantillon** [comment]
Hi ixelero,

Could you give an idea of what you would expect to happen?

If you are passing a string value when an integer value is expected the route binding will fail for obvious reasons. An error being throw and a 500 response is the same behavior as ASP.Net in this situation.

Any additional information about what you were expecting would help James and others to help you.

Thanks,

Matt.

**Comment by JamesRandall** [comment]
Thinking about this it probably ought to return a Bad Request. What are peoples thoughts?

**Comment by mcantillon** [comment]
Having done a little reading and thought, I was incorrect to say ASP.Net throws an error, it actually passes null's in to the handler on binding failure. 
I think it would be best to follow ASP.Net and pass null's on binding failure by default and maybe allow an extension point for the developer to return a Bad Request result or another HTTP response if they like.

Thoughts?

**Comment by ixelero** [comment]
> Thinking about this it probably ought to return a Bad Request. What are peoples thoughts?

I think it is the best way to resolve this issue.

**Comment by magoja2** [comment]
Hello all,
I think to have just a bad request it is not the best idea.

We should have some ability to add some additional information to bad request.

**Comment by JamesRandall** [comment]
I've implemented this to return bad request along with details of the error in the response body. In the upcoming release.

**Comment by ixelero** [comment]
Great! Tnx, James.

**Comment by JamesRandall** [comment]
Addressed in v3.0.4-beta1. Thanks!

**Comment by ArryMatt** [comment]
Not sure id I am doing something wrong here, but upgraded to the latest version and still getting a 500 with:

[15/07/2019 08:51:27] Executed 'Site' (Failed, Id=15312679-3d9b-4cc0-9b17-6a9cae4a4238)
[15/07/2019 08:51:27] System.Private.CoreLib: Exception while executing function: Site. Newtonsoft.Json: Error converting value "Fred" to type 'System.Guid'. Path 'SiteId', line 4, position 20. Newtonsoft.Json: Could not cast or convert from System.String to System.Guid.

My references are:
    <PackageReference Include="FunctionMonkey" Version="3.0.5-beta2" />
    <PackageReference Include="FunctionMonkey.Compiler" Version="3.0.5-beta2" />
    <PackageReference Include="FunctionMonkey.FluentValidation" Version="3.0.5-beta2" />

**Comment by JamesRandall** [comment]
That's really odd. Can you share me details of the configuration, the command, and how you're calling it please? (if not appropriate for here happy to take a look on email or Skype)

**Comment by ArryMatt** [comment]
So, all of my commands use a base command as they all need to have a SiteId.  The command I was using to test this is SiteQuery:
`
    public class SiteQuery : BaseCommand<Site>
    {
    }
`

BaseCommand has two flavours:
`
    public abstract class BaseCommand<T> : Base, ICommand<T>
    {
    }
    public abstract class BaseCommand : Base, ICommand
    {
    }
`

And the Base class has the property of SiteId, as well as other:
`
    public abstract class Base : ISiteCommandContext, IUserCommandContext
    {
        public Guid SiteId { get; set; }
`

Happy to Skype or Live Share, if you can do that on a Mac :-)

**Comment by JamesRandall** [comment]
Resolved in v3.0.6-beta3
